export const deliveryTableData = [
  {
    name: "John Doe",
    product: "Iphone 11 pro ",
    packageID: "BW-TRSF-WTA2W",
    package: "Bag of Rice",
    date: "12 Jun 25 15:00:00",
    amountPaid: "120,000.00",
    amount: "1",
    deliveryFee: "10,000",
    status: "successful",
    location: "14th Brown street, bright hope Warri Delta State",
  },
  {
    name: "John Doe",
    product: "Iphone 11 pro ",
    packageID: "BW-TRSF-WTA2W",
    package: "Bag of Rice",
    date: "12 Jun 25 15:00:00",
    amountPaid: "120,000.00",
    amount: "1",
    deliveryFee: "10,000",
    status: "successful",
    location: "14th Brown street, bright hope Warri Delta State",
  },
  {
    name: "John Doe",
    product: "Iphone 11 pro ",
    packageID: "BW-TRSF-WTA2W",
    package: "Bag of Rice",
    date: "12 Jun 25 15:00:00",
    amountPaid: "120,000.00",
    amount: "1",
    deliveryFee: "10,000",
    status: "successful",
    location: "14th Brown street, bright hope Warri Delta State",
  },
  {
    name: "John Doe",
    product: "Iphone 11 pro ",
    packageID: "BW-TRSF-WTA2W",
    package: "Bag of Rice",
    date: "12 Jun 25 15:00:00",
    amountPaid: "120,000.00",
    amount: "1",
    deliveryFee: "10,000",
    status: "successful",
    location: "14th Brown street, bright hope Warri Delta State",
  },
  {
    name: "John Doe",
    product: "Iphone 11 pro ",
    packageID: "BW-TRSF-WTA2W",
    package: "Bag of Rice",
    date: "12 Jun 25 15:00:00",
    amountPaid: "120,000.00",
    amount: "1",
    deliveryFee: "10,000",
    status: "successful",
    location: "14th Brown street, bright hope Warri Delta State",
  },
  {
    name: "John Doe",
    product: "Iphone 11 pro ",
    packageID: "BW-TRSF-WTA2W",
    package: "Bag of Rice",
    date: "12 Jun 25 15:00:00",
    amountPaid: "120,000.00",
    amount: "1",
    deliveryFee: "10,000",
    status: "successful",
    location: "14th Brown street, bright hope Warri Delta State",
  },
  {
    name: "John Doe",
    product: "Iphone 11 pro ",
    packageID: "BW-TRSF-WTA2W",
    package: "Bag of Rice",
    date: "12 Jun 25 15:00:00",
    amountPaid: "120,000.00",
    amount: "1",
    deliveryFee: "10,000",
    status: "successful",
    location: "14th Brown street, bright hope Warri Delta State",
  },
  {
    name: "John Doe",
    product: "Iphone 11 pro ",
    packageID: "BW-TRSF-WTA2W",
    package: "Bag of Rice",
    date: "12 Jun 25 15:00:00",
    amountPaid: "120,000.00",
    amount: "1",
    deliveryFee: "10,000",
    status: "successful",
    location: "14th Brown street, bright hope Warri Delta State",
  },
];
